server:
  port: 8080
spring:
  application:
    name: coin-common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/coin-exchange
    username: root
    password: Ltd3411??
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        enabled: false
    sentinel:
      transport:
        dashboard: sentinel-server:8858
  redis:
    host: redis-server
    port: 6380
    password: 123456
swagger2:
  basePackage: com.dolphin.controller
  name: dolphin
  url: https://github.com
  email: dolphin@dolphin.com
  title: Coin-Common的模型测试
  description: Coin-Common模块
  version: 1.0
  termsOfServiceUrl: www.dolphin.com
mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl mapper-locations: classpath:/mapper/*Mapper.xml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local: # 本地的缓存的实现
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote: # 远程的缓存的实现
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}